import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'inverse-on-surface': '#121c2a',
        'on-tertiary-fixed': '#002113',
        'tertiary-fixed': '#6ffbbe',
        'on-tertiary-container': '#83ffc6',
        'outline-variant': '#414753',
        'on-secondary-fixed-variant': '#004e5c',
        'on-secondary-container': '#acedff',
        'surface-container-high': '#27313f',
        'outline': '#8c919e',
        'secondary-fixed': '#acedff',
        'surface': '#121c2a',
        'primary-container': '#0066cc',
        'inverse-surface': '#eaf1ff',
        'on-primary': '#ffffff',
        'error-container': '#93000a',
        'secondary-container': '#004e5c',
        'surface-container': '#1e293b',
        'on-surface-variant': '#c1c6d5',
        'on-primary-container': '#dfe8ff',
        'surface-container-highest': '#374151',
        'on-background': '#f8f9ff',
        'surface-tint': '#aac7ff',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#00458e',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#001f26',
        'surface-container-lowest': '#0b121d',
        'surface-container-low': '#121c2a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#005c3e',
        'secondary-fixed-dim': '#4cd7f6',
        'on-surface': '#f8f9ff',
        'tertiary': '#6ffbbe',
        'primary-fixed-dim': '#aac7ff',
        'secondary': '#4cd7f6',
        'inverse-primary': '#005cba',
        'surface-variant': '#414753',
        'primary-fixed': '#d7e3ff',
        'on-tertiary-fixed-variant': '#005236',
        'surface-dim': '#0b121d',
        'on-primary-fixed': '#001b3e',
        'error': '#ffdad6',
        'primary': '#aac7ff',
        'surface-bright': '#27313f',
        'background': '#0b121d',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'margin-desktop': '32px',
        'xl': '32px',
        'margin-mobile': '16px',
        'sm': '12px',
        'xs': '8px',
        'base': '4px',
        'xxl': '48px',
        'gutter': '24px',
        'lg': '24px',
        'md': '16px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
export default config
